{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "app-data.labels" . | nindent 4 }}
  annotations:
    demo.local/secret-scope: local-only-dummy-secret
    demo.local/secret-warning: replace-before-production
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: {{ .Values.database.owner | quote }}
  password: {{ .Values.database.localOnlyDummyPassword | quote }}
{{- end }}
