{{- if .Values.database.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.database.clusterName }}
  labels:
    {{- include "app-data.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: {{ .Values.database.instances }}
  imageName: {{ .Values.database.imageName | quote }}
  storage:
    size: {{ .Values.database.storage.size | quote }}
  bootstrap:
    initdb:
      database: {{ .Values.database.dbName | quote }}
      owner: {{ .Values.database.owner | quote }}
      secret:
        name: {{ .Values.database.secretName }}
{{- end }}
