{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      path: {{ .Values.monitoring.serviceMonitor.path | quote }}
      port: http
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
{{- end }}
